apiVersion: v1
kind: Service
metadata:
  name: demo-service-clusterip
spec:
  type: ClusterIP  # Здесь указывается тип ClusterIP
  selector:
    app: demo      # Это должно соответствовать меткам вашего пода
  ports:
  - protocol: TCP
    port: 8080      # Внутренний порт сервиса
    targetPort: 8080  # Порт контейнера

