apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 8080      # Внутренний порт сервиса
    targetPort: 8080  # Порт контейнера
    nodePort: 30080   # Публичный порт узла

apiVersion: v1
kind: Service
metadata:
  name: demo-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: demo  # Селектор, который выбирает поды с меткой app: demo
  ports:
  - protocol: TCP
    port: 8080      # Порт, на который будет доступен сервис внутри кластера
    targetPort: 8080  # Порт контейнера, на котором работает приложение
