USER-SUPPLIED VALUES:
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
image:
  pullPolicy: IfNotPresent
  repository: evgengets/neoflex
  tag: latest
ingress:
  enabled: false
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 8098
  targetPort: 8098
  type: NodePort
serviceAccount:
  create: true
  name: ""
tolerations: []
